/**
 * Interstitial detection — "Checking your browser", "Just a moment…".
 *
 * WordPress sites sit behind Cloudflare, Sucuri and Wordfence more often than
 * not, and all three answer a first request with a holding page that runs a JS
 * check and then reloads into the real site. That page has no H1, no CTAs and
 * almost no text, so scoring it produces a confident audit of the wrong
 * document — worse than an error, because it looks like a result.
 *
 * The handling is to wait for it to clear (they usually self-resolve in a few
 * seconds) and, if it does not, to say so rather than return what we have.
 *
 * No `server-only` import: these are pure string predicates with no Node
 * dependency, which is what lets them be unit-tested without a browser.
 */

export type ChallengeVerdict = {
  challenged: boolean;
  /** Which product answered, when it can be told apart. */
  vendor: string | null;
};

const MARKERS: { vendor: string | null; pattern: RegExp }[] = [
  { vendor: "cloudflare", pattern: /checking your browser/i },
  { vendor: "cloudflare", pattern: /just a moment/i },
  { vendor: "cloudflare", pattern: /verify you are human/i },
  { vendor: "cloudflare", pattern: /verifying you are human/i },
  { vendor: "cloudflare", pattern: /enable javascript and cookies to continue/i },
  { vendor: "cloudflare", pattern: /attention required!?\s*\|\s*cloudflare/i },
  { vendor: "cloudflare", pattern: /ddos protection by/i },
  { vendor: "cloudflare", pattern: /performance & security by cloudflare/i },
  { vendor: "sucuri", pattern: /sucuri website firewall/i },
  { vendor: "sucuri", pattern: /access denied.*sucuri/i },
  { vendor: "wordfence", pattern: /generated by wordfence/i },
  { vendor: "wordfence", pattern: /your access to this site has been limited/i },
  { vendor: "akamai", pattern: /access denied.*reference #\d/i },
  { vendor: "imperva", pattern: /request unsuccessful.*incapsula/i },
  // Generic wording several vendors share — detectable, but not attributable.
  { vendor: null, pattern: /please wait while we verify/i },
  { vendor: null, pattern: /one more step before/i },
];

/**
 * A challenge page is short by nature — the real site's copy is not. Requiring
 * brevity alongside a marker keeps a blog post *about* Cloudflare from being
 * mistaken for a Cloudflare interstitial.
 */
const MAX_CHALLENGE_TEXT = 1_200;

export function detectChallenge(
  title: string | null,
  text: string,
): ChallengeVerdict {
  const haystack = `${title ?? ""}\n${text}`;

  if (text.length > MAX_CHALLENGE_TEXT) return { challenged: false, vendor: null };

  for (const { vendor, pattern } of MARKERS) {
    if (pattern.test(haystack)) return { challenged: true, vendor };
  }

  return { challenged: false, vendor: null };
}

export function challengeMessage(vendor: string | null): string {
  const who = vendor ? `${vendor}'s` : "a";
  return `The site is behind ${who} browser check and did not let us through. It cannot be audited automatically.`;
}
